kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  labels:
    application: os_test_apache
  name: os_test_apache
  annotations:
    description: 'Apache-Tomcat test image'

---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: test-apache-image-build
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'os_test_apache:latest'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'httpd-24-centos7:latest'
  source:
    type: Git
    git:
      uri: 'https://github.com/y0k0yama/os_test_apache.git'
    contextDir:
      